version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION> # This placeholder is automatically replaced during CodeDeploy
        LoadBalancerInfo:
          # Name of the container to be tied to the load balancer.
          ContainerName: "<CLUSTER_NAME>-app"
          ContainerPort: 8000
