# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-versions
version: "0.2"

env:
    variables:
        DOCKER_BUILDKIT: 1

phases:
    pre_build:
        commands:
            - echo "Logging in Amazon ECR..."
            - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URL

    build:
        commands:
            - echo "Build Started..."
            - echo "Building Docker image..."
            - docker build -t $REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION .

    post_build:
        commands:
            - echo "Pushing the Docker image..."
            - docker push $REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION

            - echo "Preparing task definition..."
            - aws ecs describe-task-definition --task-definition $TASK_DEFINITION_ARN --query taskDefinition | jq '.containerDefinitions[0].image="<IMAGE1_NAME>"' > taskdef.json

            - echo "Preparing appspec..."
            - sed -i "s|<CLUSTER_NAME>|$CLUSTER_NAME|g" appspec.yml

            - echo "Writing image definitions file..."
            - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION > imagedef.json

artifacts:
    files:
      - imagedef.json
      - appspec.yml
      - taskdef.json
