# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-versions
version: "0.2"

env:
    variables:
        DOCKER_BUILDKIT: 1

phases:
    pre_build:
        commands:
            - echo "Logging in Amazon ECR..."
            - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URL

    build:
        commands:
            - echo "Build Started..."
            - echo "Building Docker image..."
            - docker build -t $REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION .

    post_build:
        commands:
            - echo "Pushing the Docker image..."
            - docker push $REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION

            - echo "Preparing task definition..."
            - sed -i "s|<PROJECT>|$PROJECT|g" taskdef.json5 # プロジェクト名
            - sed -i "s|<ENVIRONMENT>|$ENVIRONMENT|g" taskdef.json5 # デプロイ環境
            - sed -i "s|<TASK_EXECUTION_ROLE_ARN>|$TASK_EXECUTION_ROLE_ARN|g" taskdef.json5 # タスク実行ロールARN
            - sed -i "s|<TASK_ROLE_ARN>|$TASK_ROLE_ARN|g" taskdef.json5 # タスクロールARN
            - sed -i "s|<CLUSTER_NAME>|$CLUSTER_NAME|g" taskdef.json5 # ECSクラスタ名
            - sed -i "s|<ECR_IMAGE_URL>|$REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION|g" taskdef.json5 # ECRイメージURL
            - sed -i "s|<AWSLOGS_GROUP_NAME>|$AWSLOGS_GROUP_NAME|g" taskdef.json5 # CloudWatch Logsグループ名
            - sed -i "s|<AWS_REGION>|$AWS_REGION|g" taskdef.json5 # リージョン

            - echo "Preparing appspec..."
            - sed -i "s|<CLUSTER_NAME>|$CLUSTER_NAME|g" appspec.yml

            - echo "Writing image definitions file..."
            - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME "$REPOSITORY_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION" > imagedef.json

artifacts:
    files:
      - imagedef.json
      - appspec.yml
      - taskdef.json5
