# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-versions
version: "0.2"

phases:
    pre_build:
        commands:
            - echo "Logging in Amazon ECR..."
            - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URL

    build:
        commands:
            - echo "Build Started..."
            - echo "Building Docker image..."
            - docker build -t $REPOSITORY_URL:$IMAGE_TAG .

    post_build:
        commands:
            - echo "Pushing the Docker image..."
            - docker push $REPOSITORY_URL:$IMAGE_TAG
            - echo "Writing image definitions file..."
            - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URL:$IMAGE_TAG > image_definitions.json
            - echo "Reconfigure appspec..."
            - sed -i "s/<TASK_DEFINITION_ARN>/$TASK_DEFINITION_ARN/g" appspec.yml
            - sed -i "s/<CONTAINER_NAME>/$CONTAINER_NAME/g" appspec.yml
artifacts:
    files:
      - image_definitions.json
      - appspec.yml
